#!/bin/bash

# LiveDraft Arena - Conway Testnet Deployment Script
# This script builds and deploys the LiveDraft Arena contracts to Conway testnet

set -e  # Exit on any error

echo "🚀 LiveDraft Arena - Conway Testnet Deployment"
echo "=============================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
CONTRACT_PATH="contracts/livedraft-arena"
SERVICE_ENV_FILE="service/.env"
FRONTEND_CONFIG_FILE="frontend/src/config.ts"
WASM_OUTPUT_DIR="target/wasm32-unknown-unknown/release"

echo -e "${BLUE}📋 Deployment Configuration:${NC}"
echo "  Contract Path: $CONTRACT_PATH"
echo "  Target: Conway Testnet"
echo "  Service Config: $SERVICE_ENV_FILE"
echo "  Frontend Config: $FRONTEND_CONFIG_FILE"
echo ""

# Step 1: Verify prerequisites
echo -e "${YELLOW}🔍 Step 1: Verifying prerequisites...${NC}"

# Check if linera CLI is available
if ! command -v linera &> /dev/null; then
    echo -e "${RED}❌ Error: linera CLI not found. Please install Linera CLI first.${NC}"
    exit 1
fi

# Check if Rust is available
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}❌ Error: cargo not found. Please install Rust first.${NC}"
    exit 1
fi

# Check if wasm32 target is installed
if ! rustup target list --installed | grep -q "wasm32-unknown-unknown"; then
    echo -e "${YELLOW}⚠️  Installing wasm32-unknown-unknown target...${NC}"
    rustup target add wasm32-unknown-unknown
fi

echo -e "${GREEN}✅ Prerequisites verified${NC}"
echo ""

# Step 2: Build WASM contract
echo -e "${YELLOW}🔨 Step 2: Building WASM contract...${NC}"

# Clean previous builds
echo "  Cleaning previous builds..."
cargo clean

# Build the contract for WASM target
echo "  Building contract for wasm32-unknown-unknown..."
cd $CONTRACT_PATH
cargo build --target wasm32-unknown-unknown --release

# Verify WASM file was created
WASM_FILE="../../$WASM_OUTPUT_DIR/livedraft_arena.wasm"
if [ ! -f "$WASM_FILE" ]; then
    echo -e "${RED}❌ Error: WASM file not found at $WASM_FILE${NC}"
    echo "Expected file: livedraft_arena.wasm"
    echo "Available files:"
    ls -la "../../$WASM_OUTPUT_DIR/" || echo "Directory not found"
    exit 1
fi

cd ../..
echo -e "${GREEN}✅ WASM contract built successfully${NC}"
echo "  WASM file: $WASM_FILE"
echo ""

# Step 3: Check Linera wallet and chain status
echo -e "${YELLOW}🔗 Step 3: Checking Linera wallet and chain status...${NC}"

# Get current chain ID
CHAIN_ID=$(linera wallet show | grep "Default chain" | awk '{print $3}' || echo "")
if [ -z "$CHAIN_ID" ]; then
    echo -e "${RED}❌ Error: No default chain found. Please initialize your wallet and chain first.${NC}"
    echo "Run: linera wallet init --with-new-chain"
    exit 1
fi

echo "  Default chain ID: $CHAIN_ID"

# Check wallet balance (optional, for info)
echo "  Checking wallet status..."
linera wallet show

echo -e "${GREEN}✅ Wallet and chain verified${NC}"
echo ""

# Step 4: Deploy application to Conway testnet
echo -e "${YELLOW}🚀 Step 4: Deploying application to Conway testnet...${NC}"

# Deploy the application
echo "  Publishing application bytecode..."
BYTECODE_ID=$(linera publish-bytecode "$WASM_FILE")
if [ -z "$BYTECODE_ID" ]; then
    echo -e "${RED}❌ Error: Failed to publish bytecode${NC}"
    exit 1
fi

echo "  Bytecode ID: $BYTECODE_ID"

# Create the application (Lobby instance)
echo "  Creating Lobby application with ContractParameters::Lobby..."
APP_ID=$(linera create-application "$BYTECODE_ID" --json-parameters '"Lobby"')
if [ -z "$APP_ID" ]; then
    echo -e "${RED}❌ Error: Failed to create application${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Application deployed successfully${NC}"
echo "  Application ID: $APP_ID"
echo ""

# Step 5: Update service configuration
echo -e "${YELLOW}📝 Step 5: Updating service configuration...${NC}"

# Create service .env file
echo "  Creating service environment configuration..."
mkdir -p service
cat > "$SERVICE_ENV_FILE" << EOF
# LiveDraft Arena Service Configuration
# Generated by deployment script on $(date)

# Required: Deployed Application ID
LIVEDRAFT_APP_ID=$APP_ID

# Optional: Override default paths
# LINERA_WALLET_PATH=/path/to/wallet.json
# LIVEDRAFT_CHAIN_ID=$CHAIN_ID

# Optional: Service configuration
# PORT=8080
EOF

echo -e "${GREEN}✅ Service configuration created: $SERVICE_ENV_FILE${NC}"
echo ""

# Step 6: Update frontend configuration
echo -e "${YELLOW}📝 Step 6: Updating frontend configuration...${NC}"

# Create frontend config file
echo "  Creating frontend configuration..."
mkdir -p frontend/src
cat > "$FRONTEND_CONFIG_FILE" << EOF
// LiveDraft Arena Frontend Configuration
// Generated by deployment script on $(date)

export const LIVEDRAFT_CONFIG = {
  // Deployed Application ID (same for Lobby and DraftRoom)
  APP_ID: '$APP_ID',
  
  // Conway Testnet Configuration
  GRAPHQL_ENDPOINT: 'http://localhost:8080/graphql',
  
  // Deployment Information
  DEPLOYMENT: {
    BYTECODE_ID: '$BYTECODE_ID',
    CHAIN_ID: '$CHAIN_ID',
    DEPLOYED_AT: '$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
    NETWORK: 'Conway Testnet'
  }
} as const;

// Export individual values for convenience
export const APP_ID = LIVEDRAFT_CONFIG.APP_ID;
export const GRAPHQL_ENDPOINT = LIVEDRAFT_CONFIG.GRAPHQL_ENDPOINT;
EOF

echo -e "${GREEN}✅ Frontend configuration created: $FRONTEND_CONFIG_FILE${NC}"
echo ""

# Step 7: Create deployment summary
echo -e "${YELLOW}📄 Step 7: Creating deployment summary...${NC}"

# Save deployment info to file
DEPLOY_INFO_FILE="deployment_info.json"
cat > "$DEPLOY_INFO_FILE" << EOF
{
  "deployment": {
    "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
    "network": "Conway Testnet",
    "status": "success"
  },
  "contract": {
    "bytecode_id": "$BYTECODE_ID",
    "application_id": "$APP_ID",
    "chain_id": "$CHAIN_ID",
    "wasm_file": "$WASM_FILE"
  },
  "configuration": {
    "service_env": "$SERVICE_ENV_FILE",
    "frontend_config": "$FRONTEND_CONFIG_FILE"
  },
  "endpoints": {
    "conway_testnet": "https://conway-testnet.linera.net:8080",
    "local_service": "http://localhost:8080/graphql"
  }
}
EOF

echo -e "${GREEN}✅ Deployment summary created: $DEPLOY_INFO_FILE${NC}"
echo ""

# Step 8: Final deployment summary
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo "================================"
echo ""
echo -e "${BLUE}📊 Deployment Summary:${NC}"
echo "  Bytecode ID:     $BYTECODE_ID"
echo "  Application ID:  $APP_ID"
echo "  Chain ID:        $CHAIN_ID"
echo "  Network:         Conway Testnet"
echo ""
echo -e "${BLUE}📋 Application Details:${NC}"
echo "  Contract Type:   Unified (Lobby + DraftRoom)"
echo "  Lobby Instance:  $APP_ID on chain $CHAIN_ID"
echo "  DraftRooms:      $APP_ID on microchains (created by lobby)"
echo "  Parameters:      ContractParameters::Lobby used for creation"
echo ""
echo -e "${BLUE}🔧 Configuration Files Created:${NC}"
echo "  Service:         $SERVICE_ENV_FILE"
echo "  Frontend:        $FRONTEND_CONFIG_FILE"
echo "  Summary:         $DEPLOY_INFO_FILE"
echo ""
echo -e "${BLUE}🚀 Next Steps:${NC}"
echo "  1. Start service: cd service && cargo run"
echo "  2. Start frontend: cd frontend && npm run dev"
echo "  3. Test deployment: Open http://localhost:3000"
echo ""
echo -e "${YELLOW}💡 Usage Notes:${NC}"
echo "  • Service reads LIVEDRAFT_APP_ID from $SERVICE_ENV_FILE"
echo "  • Frontend imports APP_ID from $FRONTEND_CONFIG_FILE"
echo "  • Both components use the same deployed application"
echo "  • Lobby operations execute on chain $CHAIN_ID"
echo "  • DraftRoom operations execute on individual microchains"
echo ""
echo -e "${GREEN}✅ LiveDraft Arena is now live on Conway testnet!${NC}"
echo -e "${BLUE}🔗 Application ID: $APP_ID${NC}"